name: Setup Python and Dependencies
description: Install uv and sync dependencies

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
